const mongoose = require('mongoose')

const userSchema = new mongoose.Schema({
  email: { type: String, unique: true, required: true },
  firstName: { type: String, minlength: 3, required: true },
  lastName: { type: String, minlength: 2, required: true },
  password: { type: String, minlength: 6, required: true },
  mobileNumber: { type: Number, minlength: 7, required: false },
  timeZone: { type: String, required: false },
  businessPhone: { type: Number, minlength: 7, required: false },
  webAddress: { type: String, minlength: 3, required: false },
  title: { type: String, minlength: 5, required: false },
  affiliateId: { type: String, required: false },
  url: { type: String, required: false },
  age: { type: String, minlength: 7, required: false },
  cnic: { type: String, minlength: 7, required: false },
  program: { type: String, minlength: 7, required: false },
  name: { type: String, minlength: 7, required: false },
  gender: { type: String, minlength: 7, required: false },
  address: { type: String, minlength: 7, required: false },
  city: { type: String, minlength: 7, required: false },
  state: { type: String, minlength: 7, required: false },
  district: { type: String, minlength: 7, required: false },
  last_Degree: { type: String, minlength: 7, required: false },
  name_institute: { type: String, minlength: 7, required: false },
  roll_Number: { type: String, minlength: 7, required: false },
  completion: { type: String, minlength: 7, required: false },
  total_marks: { type: String, minlength: 7, required: false },
  obtained_marks: { type: String, minlength: 7, required: false },
  verification: { type: String, minlength: 7, required: false },
  board: { type: String, minlength: 7, required: false },
  Province: { type: String, minlength: 7, required: false },
})
module.exports = mongoose.model('User', userSchema)